### ISSUE TITLE
Reorganize the help system

### ISSUE THREAD

**Issue by pcav** [qgis/qgis4.0_api#62]
The idea is to unify the manual and the help, so the user can go to the appropriate documentation page directly from QGIS interface.
Writing docs for Processing algs would be also easier, as it can be done in rst (or markdown) and displayed in Processing help, as it happens now for e.g. GRASS manpages.

**Comment by rduivenvoorde** [comment]
We have this idea about a system online (or possibly via a per language downloaded zip), see

https://github.com/qgis/QGIS-Enhancement-Proposals/issues/51

I still think this is a good idea

**Comment by pcav** [comment]
Agreed. IMHO we should really make it for Q3.

**Comment by alexbruy** [comment]
PR which implements qgis/QGIS-Enhancement-Proposals#51 merged in master. So we can start with adopting docs, merging context help and linking them from QGIS

**Comment by m-kuhn** [comment]
Thanks @alexbruy for the excellent work!

**Comment by nyalldawson** [comment]
This was done for 3.0
